### ISSUE TITLE
Transfert

### ISSUE THREAD

**Issue by Yomguithereal** [luccitan/graphology-communities#8]
Salut @luccitan. Como va? Je vais probablement pas tarder à migrer, avec ton autorisation, ton code vers un package `graphology-communities-louvain`.

**Comment by luccitan** [comment]
Salut @Yomguithereal !
Pas de souci pour la migration, il faut bien que ce code soit utile :)
Tu fais une copie brute des fichiers, c'est cela ?
Il reste toujours des **issues** que je n'ai pas pris le temps de fix.

PS: je ne suis pas fan du nom `graphology-communities-louvain` pour le package honnêtement 😛

**Comment by Yomguithereal** [comment]
> Tu fais une copie brute des fichiers, c'est cela ?

Je vais faire mieux que ça, je vais cloner le repo et le repusher sur un autre pour garder ton historique etc. Ca où tu transfères ton repo à l'org `graphology`. Comme tu le sens.

> graphology-communities-louvain

Le pb c'est qu'il y a pas mal d'algos de communautés différents et qu'il faudrait qu'ils soient versionnés indépendemment.

**Comment by luccitan** [comment]
> Je vais faire mieux que ça, je vais cloner le repo et le repusher sur un autre pour garder ton historique etc

Cette option me plaît, fais donc :)

> Le pb c'est qu'il y a pas mal d'algos de communautés différents et qu'il faudrait qu'ils soient versionnés indépendemment.

Mmmmh.. par curiosité : quelle est plus précisément la contrainte de *versioning* ? Pourquoi devraient-ils être versionnés indépendamment ? 
L'organisation en *sous-module* comme dans `graphology-operators` n'est pas suffisante ?

**Comment by Yomguithereal** [comment]
Yo. J'ai donc fini le transfert vers `graphology-metrics` et `graphology-communities-louvain`. Normalement tu as les droits dessus. Dis-moi si jamais c'est pas le cas.

**Comment by luccitan** [comment]
J'ai le droit de modifier les _issues_.
Pour les pull requests, il n'y en a aucune donc je ne peux pas te le définir.
Quoiqu'il en soit, je n'ai pas accès au panel _Settings_, mais je suppose que c'est exclusif au propriétaire.

Ce dépôt-ci ne t'est plus utile alors?

**Comment by Yomguithereal** [comment]
Normalement tu as les droits write. Donc tu peux pusher sur le repo etc. 

> Ce dépôt-ci ne t'est plus utile alors?

A moi, non.

Merci beaucoup pour ton travail en tout cas.
